
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const ADDUSER_ERROR = 'ADDUSER_ERROR';
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT= 'SIGN_OUT';
export const REGISTER = 'REGISTER';